# Generated by Django 5.0.14 on 2026-07-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=120, verbose_name='ID кабинета')),
                ('type', models.CharField(choices=[('agency', 'Agency'), ('bm', 'BM'), ('personal', 'Personal')], default='personal', max_length=20, verbose_name='Тип')),
                ('seller', models.CharField(max_length=120, verbose_name='Селлер')),
                ('department', models.CharField(choices=[('dep_1', 'Отдел 1'), ('dep_2', 'Отдел 2')], default='dep_1', max_length=20, verbose_name='Отдел')),
                ('status', models.CharField(choices=[('issued', 'Выдан'), ('in_work', 'В работе'), ('ban', 'Бан'), ('return', 'Возврат')], default='issued', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рекламный кабинет',
                'verbose_name_plural': 'Рекламные кабинеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
